packages:
  - "frontend/**"
catalog:
  "@types/node": ^22.7.5
  "@vitejs/plugin-vue": ^5.2.0
  cac: ^6.7.14
  execa: ^9.4.0
  mermaid: ^11.4.0
  prettier: ^3.3.3
  sass: ^1.80.6
  typescript: ^5.6.3
  unbuild: ^2.0.0
  vite: ^5.4.11
  vitepress: ^1.5.0
  vitepress-plugin-mermaid: ^2.0.17
  vitest: ^2.1.2
  vue: ^3.5.13
  vue-tsc: ^2.1.10
