packages:
  - "frontend/**"
catalog:
  "@types/node": ^22.7.5
  cac: ^6.7.14
  execa: ^9.4.0
  mermaid: ^11.4.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  unbuild: ^2.0.0
  vitepress: ^1.5.0
  vitepress-plugin-mermaid: ^2.0.17
  vitest: ^2.1.2
  vue: ^3.5.12
