[versions]
jupiter = '5.11.2'
lombok = '1.18.34'

[libraries]
jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
junitPlatform = { module = "org.junit.platform:junit-platform-launcher" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
